sudo: false
language: python
cache: pip
python: 3.7
script: true
deploy:
  provider: pypi
  user: bl4ck5un
  password: $PYPI_PASSWORD
  on:
    tags: true
  distributions: "bdist_wheel"
notifications:
  email:
    on_success: never
    on_failure: always